"""create item table

Revision ID: c09708b7e010
Revises: 
Create Date: 2025-09-05 22:38:53.953273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09708b7e010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('review', name='sourcetype'), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_created_answered', 'items', ['created_at', 'answered'], unique=False)
    op.create_index(op.f('ix_items_nm_id'), 'items', ['nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_nm_id'), table_name='items')
    op.drop_index('ix_items_created_answered', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
